# Generated by Django 5.0.2 on 2025-08-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='assessor_office_link',
            field=models.URLField(blank=True, help_text='Link to assessor office page', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='building_assessed_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Building assessed value', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='land_assessed_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Land assessed value', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mailing_address',
            field=models.CharField(blank=True, help_text='Mailing address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mailing_city',
            field=models.CharField(blank=True, help_text='Mailing city', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mailing_name',
            field=models.CharField(blank=True, help_text='Mailing name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mailing_state',
            field=models.CharField(blank=True, help_text='Mailing state', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='mailing_zip',
            field=models.CharField(blank=True, help_text='Mailing ZIP code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_address',
            field=models.CharField(blank=True, help_text='Property street address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_city',
            field=models.CharField(blank=True, help_text='Property city', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_state',
            field=models.CharField(blank=True, help_text='Property state', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='square_footage_land',
            field=models.IntegerField(blank=True, help_text='Land square footage', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='taxpayer_id',
            field=models.CharField(blank=True, help_text='Taxpayer ID', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_assessed_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total assessed value', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='vacancy_type',
            field=models.CharField(blank=True, help_text='Vacancy status', max_length=50, null=True),
        ),
    ]
