# Generated by Django 5.0.2 on 2024-10-06 06:26

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDesertSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('coordinates', location_field.models.plain.PlainLocationField(max_length=63)),
                ('food_access', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Limited', 'Limited')], max_length=100)),
            ],
        ),
    ]
